#!/bin/sh
#
# Define variables
input_file=""
output_file=""

# Parse command-line arguments
while getopts ":i:o:" opt; do
  case $opt in
    i) input_file=$OPTARG ;;
    o) output_file=$OPTARG ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

# Check if input and output files are provided
if [ -z "$input_file" ] || [ -z "$output_file" ]; then
  echo "Usage: IDX_gentechReportMaker -i input_file -o output_file"
  exit 1
fi

# Set the PATH to include the required command
export PATH="/project/6007495/barekeer/pipelines/core/anaconda/bin:/project/6007495/barekeer/pipelines/tools/bin:$PATH"

echo -e "Amino_acid\tA\tC\tD\tE\tF\tG\tH\tI\tK\tL\tM\tN\tP\tQ\tR\tS\tT\tV\tW\tY" > tmp.0

for i in $(seq 1 134); do
    pos="AA${i}"
    grep -w "$pos" "$input_file" | awk -F"\t" '{print $3}' | tr '\n' '\t' | awk -v b="$pos" -v OFS="\t" '{print b, $0}' | cut -f 1-21 -d $'\t' >> tmp.0
done

echo -e "Amino_acid\tStopCodon" > tmp.1
grep ">\*" "$input_file" | sed "s/^AA//g" | sort -k1,1n -k2n,2 | tail -n+2 | head -n 134 | awk -F"\t" -v OFS="\t" '{print "AA"$1, $3}' >> tmp.1

# Execute tblmerge2 command
tblmerge2 Amino_acid tmp.0 tmp.1 > "$output_file"

# Cleanup temporary files
rm -rf tmp.*
